//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APICloudCash
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditoVivienda
    {
        public long id_CreditoVivienda { get; set; }
        public int PorcentajeInteres { get; set; }
        public int PlazoAnnios { get; set; }
        public int Monto { get; set; }
        public long id_Cliente { get; set; }
        public int id_TipoDivisa { get; set; }
        public System.DateTime FechaAprobacion { get; set; }
        public bool activo { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual TipoDivisas TipoDivisas { get; set; }
    }
}
