//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APICloudCash
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas
    {
        public long id_Cuenta { get; set; }
        public long id_Cliente { get; set; }
        public int id_TipoCuenta { get; set; }
        public int id_TipoDivisa { get; set; }
        public string numeroCuenta { get; set; }
        public bool activa { get; set; }
        public long saldo { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual TipoCuentas TipoCuentas { get; set; }
        public virtual TipoDivisas TipoDivisas { get; set; }
    }
}
