//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APICloudCash
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnvioDinero
    {
        public long id_EnvioDinero { get; set; }
        public long id_Cuenta { get; set; }
        public string nombreReceptor { get; set; }
        public string numeroCuentaReceptor { get; set; }
        public long monto { get; set; }
        public string asunto { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
    }
}
