//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APICloudCash
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturacionServicios
    {
        public int id_FacturacionServicio { get; set; }
        public int id_TipoServicio { get; set; }
        public long id_Cliente { get; set; }
        public long subtotal { get; set; }
        public long impuestos { get; set; }
        public long total { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual TipoServicios TipoServicios { get; set; }
    }
}
