//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APICloudCash
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamos
    {
        public long id_Prestamo { get; set; }
        public long id_Cliente { get; set; }
        public long id_TipoPrestamo { get; set; }
        public int id_tipoDivisa { get; set; }
        public string monto { get; set; }
        public string descripcion { get; set; }
        public int tasaInteres { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual TipoDivisas TipoDivisas { get; set; }
    }
}
