//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APICloudCash
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarjeta()
        {
            this.TCreditos = new HashSet<TCredito>();
            this.TDebitos = new HashSet<TDebito>();
        }
    
        public long id_Tarjeta { get; set; }
        public long id_Cliente { get; set; }
        public int numeroTarjeta { get; set; }
        public string nombrePoseedor { get; set; }
        public System.DateTime fechaVencimiento { get; set; }
        public short cvc { get; set; }
        public long saldo { get; set; }
        public int id_TipoDivisa { get; set; }
        public bool activa { get; set; }
        public int id_TipoTarjeta { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual TipoDivisa TipoDivisa { get; set; }
        public virtual TipoTarjeta TipoTarjeta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TCredito> TCreditos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDebito> TDebitos { get; set; }
    }
}
