//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APICloudCash
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjetas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarjetas()
        {
            this.TCreditos = new HashSet<TCreditos>();
            this.TDebitos = new HashSet<TDebitos>();
        }
    
        public long id_Tarjeta { get; set; }
        public long id_Cliente { get; set; }
        public string numeroTarjeta { get; set; }
        public string nombrePoseedor { get; set; }
        public System.DateTime fechaVencimiento { get; set; }
        public Nullable<short> cvc { get; set; }
        public long saldo { get; set; }
        public int id_TipoDivisa { get; set; }
        public bool activa { get; set; }
        public int id_TipoTarjeta { get; set; }
        public int id_MarcaTarjeta { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual MarcasTarjetas MarcasTarjetas { get; set; }
        public virtual TipoDivisas TipoDivisas { get; set; }
        public virtual TipoTarjetas TipoTarjetas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TCreditos> TCreditos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDebitos> TDebitos { get; set; }
    }
}
