//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APICloudCash
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDebito
    {
        public long id_Debito { get; set; }
        public long id_Tarjeta { get; set; }
    
        public virtual Tarjeta Tarjeta { get; set; }
    }
}
