//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APICloudCash
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamos
    {
        public long id_Prestamo { get; set; }
        public long id_Cliente { get; set; }
        public long id_TipoPrestamo { get; set; }
        public int id_tipoDivisa { get; set; }
        public string monto { get; set; }
        public string descripcion { get; set; }
        public int tasaInteres { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual TipoDivisas TipoDivisas { get; set; }
    }
}
